{
 "title": "Meshtastic",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "position",
     "query": "SELECT \n\"latitude_i\"  / 10000000.0, \n\"longitude_i\"  /  10000000.0, \n\"rssi\" FROM \"position\"\n WHERE $timeFilter  ",
     "select": [
      [
       { "params": [ "latitude_i" ], "type": "field" },
       { "params": [ " / 10000000.0" ], "type": "math" }
      ],
      [
       { "params": [ "longitude_i" ], "type": "field" },
       { "params": [ " /  10000000.0" ], "type": "math" }
      ],
      [
       { "params": [ "rssi" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Messages per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "packet_stats",
     "select": [
      [
       { "params": [ "packet_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Unique Stations  per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "unique_sender_stats",
     "select": [
      [
       { "params": [ "unique_sender_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Voltages",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "SELECT last(\"voltage\") \nFROM \"telemetry\" \nWHERE $timeFilter AND voltage >1\nGROUP BY time($__interval), \"sender\" fill(null)"
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "telemetry",
     "query": "SELECT last(\"rssi\") \nFROM \"common_data\" \nWHERE $timeFilter \nGROUP BY time($__interval), \"sender\" fill(null)",
     "select": [
      [
       { "params": [ "voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sender::tag", "operator": "=", "value": "55e52292" }
     ]
    }
   ]
  },
  {
   "title": "Channel Utilization",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "SELECT LAST(\"channel_utilization\") \nFROM \"telemetry\"\nWHERE $timeFilter AND channel_utilization <=100\nGROUP BY time($__interval), \"sender\" fill(null)  "
    }
   ]
  },
  {
   "title": "Air TX Utilization",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "SELECT mean(\"air_util_tx\") \nFROM \"telemetry\" \nWHERE $timeFilter  and \"air_util_tx\" <=100\nGROUP BY time($__interval), \"sender\" fill(null)"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "query": "SELECT last(\"temperature\") \nFROM \"telemetry\" \nWHERE $timeFilter AND temperature != 0\nGROUP BY time($__interval), \"sender\" fill(null)"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "query": "SELECT last(\"relative_humidity\") \nFROM \"telemetry\" \nWHERE $timeFilter AND relative_humidity > 0\nGROUP BY time($__interval), \"sender\" fill(null)"
    }
   ]
  },
  {
   "title": "Hops Away",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "query": "SELECT last(\"hops_away\") \nFROM \"common_data\" \nWHERE $timeFilter \nGROUP BY time($__interval), \"sender\" fill(null)"
    }
   ]
  }
 ]
}